name: Generate Debug APK

on:
  push:
    branches:
      - master # Triggers on push to your master branch
  workflow_dispatch: # Allows you to run this manually from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Grant Execute Permission to Gradlew
        run: chmod +x gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ClimbTheWorld-Debug-APK
          path: app/build/outputs/apk/debug/app-debug.apk
